// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://docyvyeqhnewfntoephh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvY3l2eWVxaG5ld2ZudG9lcGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODM1MzQsImV4cCI6MjA3MDY1OTUzNH0.Zt5OiZpNTK56KFCclpmfpkqhMua9On6L_nnoYf_8cVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});